// Barrel de servicios de dominio. Mantiene imports consistentes durante la migración.
export { profileService } from './profileService'
export { inventoryService } from './inventoryService'
export { leaderboardService } from './leaderboardService'
export { seasonService } from './seasonService'
export { colosseumService } from './colosseumService'
export { referralService } from './referralService'
export { MatchmakingService } from './matchmakingService'
export { replayService, ReplayService } from './replayService'
export { adminService } from './adminService'
export { accountService } from './accountService'
export { publicService } from './publicService'
export { battleService } from './battleService'
export { marketplaceService } from './marketplaceService'
export { lotteryService } from './lotteryService'
export { shopService } from './shopService'
export { tournamentService } from './tournamentService'
