import type { PlantConfig, PlantId, EnemyPlantConfig, EnemyPlantType } from '../types/game'

export const PLANT_CONFIGS: Record<PlantId, PlantConfig> = {
  sunflower: {
    id: 'sunflower',
    name: 'Sunflower',
    cost: 50,
    cooldownMs: 5000,
    maxHp: 300,
    category: 'producer',
    icon: '/game-assets/greenfoot/sunflowerpacket1.png',
    packetActive: '/game-assets/greenfoot/sunflowerpacket1.png',
    packetDisabled: '/game-assets/greenfoot/sunflowerpacket1.png',
    sprite: '/game-assets/greenfoot/transparentsunflower.png',
    description: 'Genera soles adicionales para colocar más plantas.',
  },
  peashooter: {
    id: 'peashooter',
    name: 'Peashooter',
    cost: 100,
    cooldownMs: 7500,
    maxHp: 300,
    category: 'ranged',
    attackSpeedMs: 1400,
    damage: 25,
    icon: '/game-assets/greenfoot/peashooterpacket1.png',
    packetActive: '/game-assets/greenfoot/peashooterpacket1.png',
    packetDisabled: '/game-assets/greenfoot/peashooterpacket1.png',
    sprite: '/game-assets/greenfoot/transparentpeashooter.png',
    description: 'Dispara guisantes a los enemigos que se acercan.',
  },
  repeater: {
    id: 'repeater',
    name: 'Repeater',
    cost: 200,
    cooldownMs: 7500,
    maxHp: 300,
    category: 'ranged',
    attackSpeedMs: 1200,
    damage: 25,
    icon: '/game-assets/greenfoot/repeaterpacket1.png',
    packetActive: '/game-assets/greenfoot/repeaterpacket1.png',
    packetDisabled: '/game-assets/greenfoot/repeaterpacket1.png',
    sprite: '/game-assets/greenfoot/transparentrepeater.png',
    description: 'Dispara dos guisantes seguidos a gran velocidad.',
  },
  wallnut: {
    id: 'wallnut',
    name: 'Wall-nut',
    cost: 50,
    cooldownMs: 15000,
    maxHp: 1200,
    category: 'defensive',
    icon: '/game-assets/greenfoot/walnutpacket1.png',
    packetActive: '/game-assets/greenfoot/walnutpacket1.png',
    packetDisabled: '/game-assets/greenfoot/walnutpacket1.png',
    sprite: '/game-assets/greenfoot/transparentwalnut.png',
    description: 'Una cáscara dura que se queda fija como TANQUE protegiendo a tus otras plantas.',
  },
  melonpult: {
    id: 'melonpult',
    name: 'Melon-pult',
    cost: 375,
    cooldownMs: 10000,
    maxHp: 350,
    category: 'ranged',
    attackSpeedMs: 2400,
    damage: 80,
    icon: '/game-assets/greenfoot/melonpacket1.png',
    packetActive: '/game-assets/greenfoot/melonpacket1.png',
    packetDisabled: '/game-assets/greenfoot/melonpacket1.png',
    sprite: '/game-assets/images/Plants/melon_pult.png',
    description: 'Lanza sandías pesadas que infligen daño de área.',
  },
  chomper: {
    id: 'chomper',
    name: 'Cactus',
    cost: 150,
    cooldownMs: 8000,
    maxHp: 500,
    category: 'melee',
    moveSpeed: 4.5, // % per second walking towards P2 base
    attackSpeedMs: 1100,
    damage: 35,
    icon: '/game-assets/greenfoot/cactuspacket1.png',
    packetActive: '/game-assets/greenfoot/cactuspacket1.png',
    packetDisabled: '/game-assets/greenfoot/cactuspacket1.png',
    sprite: '/game-assets/greenfoot/cactus1.png',
    description: 'Planta atacante que CAMINA hacia la base enemiga disparando espinas continuamente.',
  },
  bonkchoy: {
    id: 'bonkchoy',
    name: 'Bonk Choy',
    cost: 150,
    cooldownMs: 7500,
    maxHp: 600,
    category: 'melee',
    moveSpeed: 5.0,
    attackSpeedMs: 700,
    damage: 65,
    icon: '/game-assets/greenfoot/bonkchoypacket1.png',
    packetActive: '/game-assets/greenfoot/bonkchoypacket1.png',
    packetDisabled: '/game-assets/greenfoot/bonkchoypacket1.png',
    sprite: '/game-assets/greenfoot/bonkchoy1.png',
    description: 'Lanza puñetazos rabiosos y veloces a los enemigos cercanos.',
  },
  garlic: {
    id: 'garlic',
    name: 'Squash',
    cost: 50,
    cooldownMs: 7500,
    maxHp: 300,
    category: 'melee',
    moveSpeed: 6.0,
    damage: 600,
    icon: '/game-assets/greenfoot/garlicpacket1.png',
    packetActive: '/game-assets/greenfoot/garlicpacket1.png',
    packetDisabled: '/game-assets/greenfoot/garlicpacket1.png',
    sprite: '/game-assets/greenfoot/garlic1.png',
    description: 'Salta sobre el primer enemigo y lo aplasta con impacto masivo.',
  },
  squash: {
    id: 'squash',
    name: 'Potato Mine',
    cost: 25,
    cooldownMs: 20000,
    maxHp: 300,
    category: 'defensive',
    damage: 1800,
    icon: '/game-assets/greenfoot/potatopacket1.png',
    packetActive: '/game-assets/greenfoot/potatopacket1.png',
    packetDisabled: '/game-assets/greenfoot/potatopacket1.png',
    sprite: '/game-assets/greenfoot/potato1.png',
    description: 'Se clava en la tierra y requiere tiempo para armarse. Al ser pisada por un enemigo, explota causando daño masivo.',
  },
  twinsunflower: {
    id: 'twinsunflower',
    name: 'Twin Sunflower',
    cost: 125,
    cooldownMs: 10000,
    maxHp: 300,
    category: 'producer',
    icon: '/game-assets/greenfoot/twinsunflowerpacket1.png',
    packetActive: '/game-assets/greenfoot/twinsunflowerpacket1.png',
    packetDisabled: '/game-assets/greenfoot/twinsunflowerpacket1.png',
    sprite: '/game-assets/greenfoot/twinsunflower1.png',
    description: 'Genera el doble de soles que un girasol común.',
  },
  threepeater: {
    id: 'threepeater',
    name: 'Threepeater',
    cost: 325,
    cooldownMs: 7500,
    maxHp: 300,
    category: 'ranged',
    attackSpeedMs: 1400,
    damage: 75,
    icon: '/game-assets/greenfoot/threepeaterpacket1.png',
    packetActive: '/game-assets/greenfoot/threepeaterpacket1.png',
    packetDisabled: '/game-assets/greenfoot/threepeaterpacket1.png',
    sprite: '/game-assets/greenfoot/threepeater1.png',
    description: 'Dispara guisantes en tres carriles adyacentes simultáneamente.',
  },
  tallnut: {
    id: 'tallnut',
    name: 'Tall-nut',
    cost: 125,
    cooldownMs: 20000,
    maxHp: 2400,
    category: 'defensive',
    icon: '/game-assets/greenfoot/tallnutpacket1.png',
    packetActive: '/game-assets/greenfoot/tallnutpacket1.png',
    packetDisabled: '/game-assets/greenfoot/tallnutpacket1.png',
    sprite: '/game-assets/greenfoot/transparenttallnut.png',
    description: 'Nuez gigante defensiva ultra resistente. Absorbe una cantidad enorme de daño frente a los enemigos.',
  },
  jalapeno: {
    id: 'jalapeno',
    name: 'Jalapeño',
    cost: 125,
    cooldownMs: 15000,
    maxHp: 1,
    category: 'defensive',
    damage: 1000,
    icon: '/game-assets/plants/jalapeno_hd.png',
    packetActive: '/game-assets/plants/jalapeno_hd.png',
    packetDisabled: '/game-assets/plants/jalapeno_hd.png',
    sprite: '/game-assets/plants/jalapeno_hd.png',
    description: 'Planta Explosiva de Carril de 1 Solo Uso. Al colocarlo en el carril, explota quemando la línea entera e infligiendo 1000 de daño masivo antes de desaparecer.',
  },
  iceberglettuce: {
    id: 'iceberglettuce',
    name: 'Lechuga Helada',
    cost: 0,
    cooldownMs: 12000,
    maxHp: 1,
    category: 'defensive',
    damage: 0,
    icon: '/game-assets/plants/iceberglettuce_hd.png',
    packetActive: '/game-assets/plants/iceberglettuce_hd.png',
    packetDisabled: '/game-assets/plants/iceberglettuce_hd.png',
    sprite: '/game-assets/plants/iceberglettuce_hd.png',
    description: 'Planta de Hielo de 0 Soles de 1 Solo Uso. Al colocarse en el campo, congela a todos los enemigos durante 7 segundos, dejándolos completamente inmóviles e incapaces de atacar o actuar.',
  },
  aloe: {
    id: 'aloe',
    name: 'Aloe Curandera',
    cost: 100,
    cooldownMs: 8000,
    maxHp: 400,
    category: 'producer',
    damage: 0,
    icon: '/game-assets/plants/aloe_hd.png',
    packetActive: '/game-assets/plants/aloe_hd.png',
    packetDisabled: '/game-assets/plants/aloe_hd.png',
    sprite: '/game-assets/plants/aloe_hd.png',
    description: 'Planta de Soporte Curativo Inteligente. Regenera la salud de las plantas heridas en su carril.',
  },
}

export const ENEMY_PLANT_CONFIGS: Record<EnemyPlantType, EnemyPlantConfig> = {
  enemy_sunflower: {
    type: 'enemy_sunflower',
    name: 'Girasol Enemigo',
    cost: 50,
    maxHp: 300,
    speed: 0,
    damage: 0,
    sprite: '/game-assets/greenfoot/transparentsunflower.png',
    rewardSun: 25,
    category: 'producer',
  },
  enemy_peashooter: {
    type: 'enemy_peashooter',
    name: 'Guisantera Enemiga',
    cost: 100,
    maxHp: 260,
    speed: 0,
    damage: 30,
    sprite: '/game-assets/greenfoot/transparentpeashooter.png',
    rewardSun: 25,
    category: 'ranged',
  },
  enemy_wallnut: {
    type: 'enemy_wallnut',
    name: 'Nuez Enemiga',
    cost: 50,
    maxHp: 850,
    speed: 0,
    damage: 25,
    sprite: '/game-assets/greenfoot/transparentwalnut.png',
    rewardSun: 35,
    category: 'defensive',
  },
  enemy_chomper: {
    type: 'enemy_chomper',
    name: 'Cactus Enemigo',
    cost: 150,
    maxHp: 480,
    speed: 3.5,
    damage: 90,
    sprite: '/game-assets/greenfoot/cactus1.png',
    rewardSun: 40,
    category: 'melee',
  },
  enemy_melonpult: {
    type: 'enemy_melonpult',
    name: 'Melón Enemigo',
    cost: 375,
    maxHp: 380,
    speed: 0,
    damage: 70,
    sprite: '/game-assets/images/Plants/melon_pult.png',
    rewardSun: 50,
    category: 'ranged',
  },
}

export const INITIAL_SUN = 0
export const INITIAL_BASE_HP = 600
export const SUN_VALUE = 25

export const LANES_CONFIG = [
  { id: 0, topPct: 20, heightPct: 19.33 },
  { id: 1, topPct: 39.33, heightPct: 19.34 },
  { id: 2, topPct: 58.67, heightPct: 19.33 },
]

export const BASE_LEFT_END_X = 15
export const BASE_RIGHT_START_X = 85
export const FIELD_WIDTH_PCT = BASE_RIGHT_START_X - BASE_LEFT_END_X
export const TOTAL_COLUMNS = 12
export const P1_COLUMNS = 6
export const P2_COLUMNS = 6

export function getScaledPlantConfig(plantId: PlantId, level: number = 0): PlantConfig {
  const base = PLANT_CONFIGS[plantId]
  if (!base || level <= 0) return base

  const scale = 1 + level * 0.15

  return {
    ...base,
    maxHp: Math.round(base.maxHp * scale),
    damage: base.damage !== undefined ? Math.round(base.damage * scale) : undefined,
  }
}
